const Command = require("../../structures/Command.js");


class Badge extends Command {
  constructor(...args) {
    super(...args, {
      description: "Get a themed badge from robohash.org",
      usage: "badge [@user] [set]",
      extendedHelp: "These are your unique hashes generated by your user ID.",
      aliases: ["robohash"]
    });
  }

  async run(msg, [user, set = 1]) {
    user = await this.verifyUser(msg, user, true);

    if(isNaN(parseInt(set)) || (parseInt(set) < 0 || parseInt(set) > 5))
      return msg.send("Set must be a number between 1 to 5");

    return msg.send(this.client.embed()
      .setImage(`https://robohash.org/${user.id}?set=set${set}`)
      .setTitle(`${user.tag}'s unique RoboHash.org Set ${set} Avatar.`)
      .setFooter(`Requested by ${msg.author.tag}`, msg.author.displayAvatarURL({ size: 64 }))
      .setTimestamp());
  }
}

module.exports = Badge;
